import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'si' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Common
    'welcome': 'Welcome',
    'login': 'Login',
    'logout': 'Logout',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'search': 'Search',
    'filter': 'Filter',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'apply': 'Apply',
    'approve': 'Approve',
    'reject': 'Reject',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    
    // Portal Names
    'agency_portal': 'Agency Portal',
    'worker_portal': 'Existing Workers',
    'jobseeker_portal': 'Job Seekers',
    'admin_portal': 'Admin Portal',
    
    // Complaints
    'submit_complaint': 'Submit Complaint',
    'my_complaints': 'My Complaints',
    'complaint_to_agency': 'Complaint to Agency',
    'escalate_to_admin': 'Escalate to Admin',
    'complaint_type': 'Complaint Type',
    'complaint_description': 'Description',
    
    // Jobs
    'browse_jobs': 'Browse Jobs',
    'post_job': 'Post Job',
    'job_title': 'Job Title',
    'location': 'Location',
    'salary': 'Salary',
    'positions': 'Positions',
    'free_posts_remaining': 'Free Posts Remaining',
    
    // Alerts
    'emergency_alerts': 'Emergency Alerts',
    'create_alert': 'Create Alert',
    'alert_title': 'Alert Title',
    'alert_message': 'Alert Message',
    'send_notification': 'Send Notification',

    // Home
    'home_platform_tagline': 'Migrant Worker Management Platform',
    'home_hero_title': 'Connecting Government, Agencies, and Workers',
    'home_hero_description': 'A comprehensive platform to ensure worker welfare, streamline agency operations, and enable effective government oversight of migrant workers.',
    'home_access_dashboard': 'Access Dashboard',
    'home_agency_card_desc': 'Manage workers, post job opportunities, and communicate with government.',
    'home_worker_card_desc': 'Submit complaints, browse job opportunities, and access support services.',
    'home_jobseeker_card_desc': 'Browse and apply for job opportunities, track your applications.',
    'home_key_features': 'Key Features',
    'home_feature_complaints_title': 'Complaint Management',
    'home_feature_complaints_desc': 'Workers can report payment, health, workplace, and infrastructure issues.',
    'home_feature_updates_title': 'Real-time Updates & Notifications',
    'home_feature_updates_desc': 'Instant alerts and reporting notifications for workers and agencies.',
    'home_feature_agency_title': 'Agency Monitoring',
    'home_feature_agency_desc': 'Government oversight of agency performance and compliance.',
    'home_about_title': 'LabourLink',
    'home_about_desc': 'Connecting workers, agencies, and government to ensure welfare and rights of migrant workers through streamlined services and oversight.',
    'home_contact_title': 'Contact Us',
    'home_hotline_label': 'Hotline',
    'home_office_label': 'Office',
    'home_support_email': 'support@labourlink.gov.lk',
    'home_complaints_email': 'complaints@labourlink.gov.lk',
    'home_ministry_address': 'Ministry of Labour & Foreign Employment\nColombo, Sri Lanka',
    'home_quick_links_title': 'Quick Links',
    'home_about_link': 'About Us',
    'home_worker_rights_link': 'Worker Rights',
    'home_agency_registration_link': 'Agency Registration',
    'home_support_services_link': 'Support Services',
    'home_faqs_link': 'FAQs',
    'home_contact_support_link': 'Contact Support',
    'home_legal_title': 'Legal',
    'home_privacy_link': 'Privacy Policy',
    'home_terms_link': 'Terms of Service',
    'home_data_protection_link': 'Data Protection',
    'home_cookie_policy_link': 'Cookie Policy',
    'home_accessibility_link': 'Accessibility',
    'home_disclaimer_link': 'Disclaimer',
    'home_rights_reserved': '© 2026 LabourLink. All rights reserved.',
    'home_available': 'Available 24/7',
    'home_emergency': 'Emergency: +94-800-HELP',

    // Login
    'back_to_home': 'Back to Home',
    'sign_in': 'Sign In',
    'signing_in': 'Signing in...',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'worker_signin_subtitle': 'Sign in to access your account',
    'jobseeker_signin_subtitle': 'Sign in to find your next opportunity',
    'agency_signin_subtitle': 'Sign in to manage your agency',
    'admin_signin_subtitle': 'LabourLink',
    'admin_authorized_only': 'Authorized Personnel Only',
    'worker_id_label': 'Worker ID / Passport Number',
    'worker_id_placeholder': 'Enter your Worker ID',
    'worker_id_hint': 'Use the ID provided by your agency or government',
    'jobseeker_id_label': 'Applicant ID / Email',
    'jobseeker_id_placeholder': 'Enter your ID or email',
    'jobseeker_id_hint': 'Use the ID provided during registration',
    'agency_email_label': 'Agency Email',
    'agency_email_placeholder': 'agency@example.com',
    'admin_id_label': 'Admin ID',
    'admin_id_placeholder': 'Enter your admin ID',
    'password_label': 'Password',
    'password_placeholder': 'Enter your password',
    'register_worker': 'Register as worker',
    'register_jobseeker': 'Register as job seeker',
    'register_agency': 'Register your agency',
    'dont_have_account': "Don't have an account?",
    'need_help': 'Need Help?',
    'support_hotline': 'Contact our 24/7 support hotline',
    'available_languages': 'Available in multiple languages for your convenience',
    'agency_help_prompt': 'Need help? Contact Support:',
    'admin_access_monitored': 'All access is monitored and logged',
    'admin_contact_it': "If you don't have access, contact IT support",
    'admin_secure_notice': 'This is a secure government portal. Unauthorized access is prohibited and will be prosecuted.',
    'login_success_worker': 'Login successful! Welcome to Worker Portal',
    'login_success_jobseeker': 'Login successful! Welcome to Job Seeker Portal',
    'login_success_agency': 'Login successful! Welcome to Agency Portal',
    'login_success_admin': 'Login successful! Welcome to Admin Portal',
    'login_failed': 'Login failed',
  },
  si: {
    // Common
    'welcome': 'ස්වාගතයි',
    'login': 'පිවිසෙන්න',
    'logout': 'ඉවත් වන්න',
    'submit': 'ඉදිරිපත් කරන්න',
    'cancel': 'අවලංගු කරන්න',
    'search': 'සොයන්න',
    'filter': 'පෙරහන',
    'save': 'සුරකින්න',
    'edit': 'සංස්කරණය',
    'delete': 'මකන්න',
    'view': 'බලන්න',
    'apply': 'අයදුම් කරන්න',
    'approve': 'අනුමත කරන්න',
    'reject': 'ප්‍රතික්ෂේප කරන්න',
    'pending': 'අපේක්ෂිත',
    'approved': 'අනුමත',
    'rejected': 'ප්‍රතික්ෂේප',
    
    // Portal Names
    'agency_portal': 'නියෝජිතායතන පෝටලය',
    'worker_portal': 'වත්මන් සේවකයින්',
    'jobseeker_portal': 'රැකියා සොයන්නන්',
    'admin_portal': 'පරිපාලක පෝටලය',
    
    // Complaints
    'submit_complaint': 'පැමිණිල්ලක් ඉදිරිපත් කරන්න',
    'my_complaints': 'මගේ පැමිණිලි',
    'complaint_to_agency': 'නියෝජිතායතනයට පැමිණිල්ල',
    'escalate_to_admin': 'පරිපාලකයාට යොමු කරන්න',
    'complaint_type': 'පැමිණිලි වර්ගය',
    'complaint_description': 'විස්තරය',
    
    // Jobs
    'browse_jobs': 'රැකියා බලන්න',
    'post_job': 'රැකියාවක් පළ කරන්න',
    'job_title': 'රැකියා නාමය',
    'location': 'ස්ථානය',
    'salary': 'වැටුප',
    'positions': 'තනතුරු',
    'free_posts_remaining': 'ඉතිරි නොමිලේ පළ කිරීම්',
    
    // Alerts
    'emergency_alerts': 'හදිසි ඇඟවීම්',
    'create_alert': 'ඇඟවීමක් සාදන්න',
    'alert_title': 'ඇඟවීම් මාතෘකාව',
    'alert_message': 'ඇඟවීම් පණිවිඩය',
    'send_notification': 'දැනුම්දීම යවන්න',

    // Home
    'home_platform_tagline': 'විදේශ සේවක කළමනාකරණ වේදිකාව',
    'home_hero_title': 'රජය, නියෝජිතායතන සහ සේවකයන් එකතු කරමින්',
    'home_hero_description': 'සේවක සුබසාධනය තහවුරු කරමින්, නියෝජිතායතන කටයුතු පහසුකරමින් සහ රජයේ නිරීක්ෂණය ශක්තිමත් කරන සම්පූර්ණ වේදිකාවක්.',
    'home_access_dashboard': 'ඩැෂ්බෝර්ඩ් වෙත යන්න',
    'home_agency_card_desc': 'සේවකයින් කළමනාකරණය, රැකියා පළ කිරීම සහ රජය සමඟ සන්නිවේදනය.',
    'home_worker_card_desc': 'පැමිණිලි ඉදිරිපත් කර රැකියා අවස්ථා බලන්න සහ සහාය සේවාවන් භාවිතා කරන්න.',
    'home_jobseeker_card_desc': 'රැකියා අවස්ථා බලන්න, අයදුම් කරන්න සහ අයදුම් තත්ත්වය නිරීක්ෂණය කරන්න.',
    'home_key_features': 'ප්‍රධාන ලක්ෂණ',
    'home_feature_complaints_title': 'පැමිණිලි කළමනාකරණය',
    'home_feature_complaints_desc': 'වෙලඳාම, සෞඛ්‍ය, සේවා ස්ථානය සහ පහසුකම් සම්බන්ධ ගැටලු සේවකයින්ට වාර්තා කළ හැක.',
    'home_feature_updates_title': 'තත්කාල යාවත්කාලීන කිරීම සහ දැනුම්දීම්',
    'home_feature_updates_desc': 'සේවකයින් සහ නියෝජිතායතන සඳහා වහාම දැනුම්දීම් සහ යාවත්කාලීන කිරීම්.',
    'home_feature_agency_title': 'නියෝජිතායතන නිරීක්ෂණය',
    'home_feature_agency_desc': 'නියෝජිතායතන කාර්යසාධනය සහ නියමයන් පිළිබඳ රජයේ නිරීක්ෂණය.',
    'home_about_title': 'LabourLink',
    'home_about_desc': 'සේවකයින්, නියෝජිතායතන සහ රජය එකට සම්බන්ධ කරමින් සේවක අයිතිවාසිකම් සහ සුබසාධනය තහවුරු කරයි.',
    'home_contact_title': 'අප හා සම්බන්ධ වන්න',
    'home_hotline_label': 'හදිසි දුරකථනය',
    'home_office_label': 'කාර්යාලය',
    'home_support_email': 'support@labourlink.gov.lk',
    'home_complaints_email': 'complaints@labourlink.gov.lk',
    'home_ministry_address': 'කම්කරු හා විදේශ රැකියා අමාත්‍යාංශය\nකොළඹ, ශ්‍රී ලංකාව',
    'home_quick_links_title': 'ඉක්මන් සබැඳි',
    'home_about_link': 'අප ගැන',
    'home_worker_rights_link': 'සේවක අයිතිවාසිකම්',
    'home_agency_registration_link': 'නියෝජිතායතන ලියාපදිංචිය',
    'home_support_services_link': 'සහාය සේවා',
    'home_faqs_link': 'නිතර අසන ප්‍රශ්න',
    'home_contact_support_link': 'සහාය අමතන්න',
    'home_legal_title': 'නීතිමය',
    'home_privacy_link': 'රහස්‍යතා ප්‍රතිපත්තිය',
    'home_terms_link': 'සේවා කොන්දේසි',
    'home_data_protection_link': 'දත්ත ආරක්ෂාව',
    'home_cookie_policy_link': 'කුකී ප්‍රතිපත්තිය',
    'home_accessibility_link': 'ප්‍රවේශතාව',
    'home_disclaimer_link': 'වගකීමේ ප්‍රකාශය',
    'home_rights_reserved': '© 2026 LabourLink. සියලු හිමිකම් ඇවිරිනි.',
    'home_available': '24/7 ලබා ගත හැක',
    'home_emergency': 'හදිසි: +94-800-HELP',

    // Login
    'back_to_home': 'මුල් පිටුවට',
    'sign_in': 'පිවිසෙන්න',
    'signing_in': 'පිවිසෙමින්...',
    'remember_me': 'මතක තබා ගන්න',
    'forgot_password': 'මුරපදය අමතකද?',
    'worker_signin_subtitle': 'ඔබගේ ගිණුම වෙත ප්‍රවේශ වීමට පිවිසෙන්න',
    'jobseeker_signin_subtitle': 'ඔබගේ ඊළඟ අවස්ථාව සඳහා පිවිසෙන්න',
    'agency_signin_subtitle': 'ඔබගේ නියෝජිතායතනය කළමනාකරණය සඳහා පිවිසෙන්න',
    'admin_signin_subtitle': 'LabourLink',
    'admin_authorized_only': 'අවසර ලත් පුද්ගලයින්ට පමණි',
    'worker_id_label': 'සේවක හැඳුනුම්පත / ගමන් බලපත්‍ර අංකය',
    'worker_id_placeholder': 'ඔබගේ සේවක හැඳුනුම්පත ඇතුළත් කරන්න',
    'worker_id_hint': 'ඔබගේ නියෝජිතායතනය හෝ රජය ලබාදුන් හැඳුනුම්පත භාවිතා කරන්න',
    'jobseeker_id_label': 'අයදුම්කරු හැඳුනුම්පත / ඊමේල්',
    'jobseeker_id_placeholder': 'ඔබගේ හැඳුනුම්පත හෝ ඊමේල් ඇතුළත් කරන්න',
    'jobseeker_id_hint': 'ලියාපදිංචියේදී ලබාදුන් හැඳුනුම්පත භාවිතා කරන්න',
    'agency_email_label': 'නියෝජිතායතන ඊමේල්',
    'agency_email_placeholder': 'agency@example.com',
    'admin_id_label': 'පරිපාලක හැඳුනුම්පත',
    'admin_id_placeholder': 'පරිපාලක හැඳුනුම්පත ඇතුළත් කරන්න',
    'password_label': 'මුරපදය',
    'password_placeholder': 'ඔබගේ මුරපදය ඇතුළත් කරන්න',
    'register_worker': 'සේවක ලෙස ලියාපදිංචි වන්න',
    'register_jobseeker': 'රැකියා සොයන්නෙකු ලෙස ලියාපදිංචි වන්න',
    'register_agency': 'ඔබගේ නියෝජිතායතනය ලියාපදිංචි කරන්න',
    'dont_have_account': 'ගිණුමක් නැද්ද?',
    'need_help': 'සහය අවශ්‍යද?',
    'support_hotline': '24/7 සහය දුරකථනය අමතන්න',
    'available_languages': 'ඔබගේ පහසුකම සඳහා බහු භාෂා',
    'agency_help_prompt': 'සහය අවශ්‍යද? සහය අමතන්න:',
    'admin_access_monitored': 'සියලු ප්‍රවේශ නිරීක්ෂණය කර ලොග් කරයි',
    'admin_contact_it': 'ඔබට ප්‍රවේශ නොමැති නම් IT සහය අමතන්න',
    'admin_secure_notice': 'මෙය ආරක්ෂිත රජයේ පෝටලයකි. අවසරයකින් තොර ප්‍රවේශය තහනම් සහ නීතියෙන් දඩයම් කරනු ලැබේ.',
    'login_success_worker': 'පිවිසීම සාර්ථකයි! සේවක පෝටලයට සාදරයෙන් පිළිගනිමු',
    'login_success_jobseeker': 'පිවිසීම සාර්ථකයි! රැකියා සොයන්නාගේ පෝටලයට සාදරයෙන් පිළිගනිමු',
    'login_success_agency': 'පිවිසීම සාර්ථකයි! නියෝජිතායතන පෝටලයට සාදරයෙන් පිළිගනිමු',
    'login_success_admin': 'පිවිසීම සාර්ථකයි! පරිපාලක පෝටලයට සාදරයෙන් පිළිගනිමු',
    'login_failed': 'පිවිසීම අසාර්ථකයි',
  },
  ta: {
    // Common
    'welcome': 'வரவேற்கிறோம்',
    'login': 'உள்நுழைக',
    'logout': 'வெளியேறு',
    'submit': 'சமர்ப்பிக்கவும்',
    'cancel': 'ரத்துசெய்',
    'search': 'தேடு',
    'filter': 'வடிகட்டி',
    'save': 'சேமி',
    'edit': 'திருத்து',
    'delete': 'நீக்கு',
    'view': 'பார்க்க',
    'apply': 'விண்ணப்பிக்கவும்',
    'approve': 'அனுமதி',
    'reject': 'நிராகரி',
    'pending': 'நிலுவையில்',
    'approved': 'அனுமதிக்கப்பட்டது',
    'rejected': 'நிராகரிக்கப்பட்டது',
    
    // Portal Names
    'agency_portal': 'நிறுவன போர்ட்டல்',
    'worker_portal': 'தற்போதைய பணியாளர்கள்',
    'jobseeker_portal': 'வேலை தேடுபவர்கள்',
    'admin_portal': 'நிர்வாக போர்ட்டல்',
    
    // Complaints
    'submit_complaint': 'புகார் சமர்ப்பிக்கவும்',
    'my_complaints': 'எனது புகார்கள்',
    'complaint_to_agency': 'நிறுவனத்திற்கு புகார்',
    'escalate_to_admin': 'நிர்வாகத்திற்கு அனுப்பு',
    'complaint_type': 'புகார் வகை',
    'complaint_description': 'விளக்கம்',
    
    // Jobs
    'browse_jobs': 'வேலைகளை பார்க்கவும்',
    'post_job': 'வேலை பதிவிடு',
    'job_title': 'வேலை தலைப்பு',
    'location': 'இடம்',
    'salary': 'சம்பளம்',
    'positions': 'பதவிகள்',
    'free_posts_remaining': 'இலவச பதிவுகள் மீதமுள்ளன',
    
    // Alerts
    'emergency_alerts': 'அவசர எச்சரிக்கைகள்',
    'create_alert': 'எச்சரிக்கை உருவாக்கு',
    'alert_title': 'எச்சரிக்கை தலைப்பு',
    'alert_message': 'எச்சரிக்கை செய்தி',
    'send_notification': 'அறிவிப்பை அனுப்பு',

    // Home
    'home_platform_tagline': 'புலம்பெயர் தொழிலாளர்கள் மேலாண்மை தளம்',
    'home_hero_title': 'அரசு, நிறுவனங்கள் மற்றும் தொழிலாளர்களை இணைக்கும் தளம்',
    'home_hero_description': 'தொழிலாளர் நலனைக் காக்க, நிறுவன செயல்பாடுகளை எளிதாக்க, மற்றும் அரசு மேற்பார்வையை வலுப்படுத்தும் முழுமையான தளம்.',
    'home_access_dashboard': 'டாஷ்போர்டை அணுகவும்',
    'home_agency_card_desc': 'தொழிலாளர்களை நிர்வகிக்கவும், வேலை வாய்ப்புகளை பதிவிடவும், அரசுடன் தொடர்பில் இருங்கள்.',
    'home_worker_card_desc': 'புகார்கள் சமர்ப்பிக்கவும், வேலை வாய்ப்புகளை பார்க்கவும், ஆதரவு சேவைகளை பெறவும்.',
    'home_jobseeker_card_desc': 'வேலை வாய்ப்புகளை பார்க்கவும், விண்ணப்பிக்கவும், விண்ணப்ப நிலையை கண்காணிக்கவும்.',
    'home_key_features': 'முக்கிய அம்சங்கள்',
    'home_feature_complaints_title': 'புகார் மேலாண்மை',
    'home_feature_complaints_desc': 'பணம், சுகாதாரம், பணியிடம் மற்றும் உட்கட்டமைப்பு தொடர்பான பிரச்சனைகளை தொழிலாளர்கள் புகாரளிக்கலாம்.',
    'home_feature_updates_title': 'நேரடி புதுப்பிப்புகள் மற்றும் அறிவிப்புகள்',
    'home_feature_updates_desc': 'தொழிலாளர்கள் மற்றும் நிறுவனங்களுக்கு உடனடி அறிவிப்புகள் மற்றும் புதுப்பிப்புகள்.',
    'home_feature_agency_title': 'நிறுவன கண்காணிப்பு',
    'home_feature_agency_desc': 'நிறுவன செயல்திறன் மற்றும் இணக்கம் குறித்து அரசு மேற்பார்வை.',
    'home_about_title': 'LabourLink',
    'home_about_desc': 'தொழிலாளர்கள், நிறுவனங்கள் மற்றும் அரசை இணைத்து தொழிலாளர் உரிமைகள் மற்றும் நலனைக் காக்கிறது.',
    'home_contact_title': 'எங்களை தொடர்புகொள்ளவும்',
    'home_hotline_label': 'அவசர உதவி',
    'home_office_label': 'அலுவலகம்',
    'home_support_email': 'support@labourlink.gov.lk',
    'home_complaints_email': 'complaints@labourlink.gov.lk',
    'home_ministry_address': 'தொழில் மற்றும் வெளிநாட்டு வேலைவாய்ப்பு அமைச்சகம்\nகொழும்பு, இலங்கை',
    'home_quick_links_title': 'விரைவு இணைப்புகள்',
    'home_about_link': 'எங்களை பற்றி',
    'home_worker_rights_link': 'தொழிலாளர் உரிமைகள்',
    'home_agency_registration_link': 'நிறுவன பதிவு',
    'home_support_services_link': 'ஆதரவு சேவைகள்',
    'home_faqs_link': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'home_contact_support_link': 'ஆதரவுக்கு தொடர்பு கொள்ளவும்',
    'home_legal_title': 'சட்டம்',
    'home_privacy_link': 'தனியுரிமை கொள்கை',
    'home_terms_link': 'சேவை விதிமுறைகள்',
    'home_data_protection_link': 'தரவு பாதுகாப்பு',
    'home_cookie_policy_link': 'குக்கி கொள்கை',
    'home_accessibility_link': 'அணுகுமுறை',
    'home_disclaimer_link': 'துறப்பு',
    'home_rights_reserved': '© 2026 LabourLink. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    'home_available': '24/7 கிடைக்கும்',
    'home_emergency': 'அவசரம்: +94-800-HELP',

    // Login
    'back_to_home': 'முகப்பு பக்கத்திற்கு',
    'sign_in': 'உள்நுழைக',
    'signing_in': 'உள்நுழைகிறது...',
    'remember_me': 'என்னை நினைவில் கொள்',
    'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'worker_signin_subtitle': 'உங்கள் கணக்கை அணுக உள்நுழைக',
    'jobseeker_signin_subtitle': 'உங்கள் அடுத்த வாய்ப்பை காண உள்நுழைக',
    'agency_signin_subtitle': 'உங்கள் நிறுவனத்தை நிர்வகிக்க உள்நுழைக',
    'admin_signin_subtitle': 'LabourLink',
    'admin_authorized_only': 'அனுமதிக்கப்பட்ட பணியாளர்களுக்கு மட்டும்',
    'worker_id_label': 'தொழிலாளர் அடையாளம் / கடவுச்சீட்டு எண்',
    'worker_id_placeholder': 'உங்கள் தொழிலாளர் அடையாளத்தை உள்ளிடவும்',
    'worker_id_hint': 'உங்கள் நிறுவனம் அல்லது அரசு வழங்கிய அடையாளத்தை பயன்படுத்தவும்',
    'jobseeker_id_label': 'விண்ணப்பதாரர் அடையாளம் / மின்னஞ்சல்',
    'jobseeker_id_placeholder': 'உங்கள் அடையாளம் அல்லது மின்னஞ்சலை உள்ளிடவும்',
    'jobseeker_id_hint': 'பதிவின் போது வழங்கிய அடையாளத்தை பயன்படுத்தவும்',
    'agency_email_label': 'நிறுவன மின்னஞ்சல்',
    'agency_email_placeholder': 'agency@example.com',
    'admin_id_label': 'நிர்வாக அடையாளம்',
    'admin_id_placeholder': 'உங்கள் நிர்வாக அடையாளத்தை உள்ளிடவும்',
    'password_label': 'கடவுச்சொல்',
    'password_placeholder': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'register_worker': 'தொழிலாளராக பதிவு செய்யவும்',
    'register_jobseeker': 'வேலை தேடுபவராக பதிவு செய்யவும்',
    'register_agency': 'உங்கள் நிறுவனத்தை பதிவு செய்யவும்',
    'dont_have_account': 'கணக்கு இல்லையா?',
    'need_help': 'உதவி தேவையா?',
    'support_hotline': '24/7 ஆதரவு உதவி எண்னை தொடர்புகொள்ளவும்',
    'available_languages': 'உங்கள் வசதிக்காக பல மொழிகளில் கிடைக்கிறது',
    'agency_help_prompt': 'உதவி தேவையா? ஆதரவுக்கு தொடர்பு கொள்ளவும்:',
    'admin_access_monitored': 'அனைத்து அணுகலும் கண்காணிக்கப்பட்டு பதிவிடப்படுகிறது',
    'admin_contact_it': 'அணுகல் இல்லை என்றால் IT ஆதரவுடன் தொடர்புகொள்ளவும்',
    'admin_secure_notice': 'இது பாதுகாப்பான அரசு போர்ட்டல். அனுமதியின்றி அணுகல் தடைசெய்யப்பட்டது மற்றும் சட்டப்படி நடவடிக்கை எடுக்கப்படும்.',
    'login_success_worker': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது! தொழிலாளர் போர்ட்டலுக்கு வரவேற்கிறோம்',
    'login_success_jobseeker': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது! வேலை தேடுபவர் போர்ட்டலுக்கு வரவேற்கிறோம்',
    'login_success_agency': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது! நிறுவன போர்ட்டலுக்கு வரவேற்கிறோம்',
    'login_success_admin': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது! நிர்வாக போர்ட்டலுக்கு வரவேற்கிறோம்',
    'login_failed': 'உள்நுழைவு தோல்வியடைந்தது',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
