// <auto-generated />
using System;
using LabourLinkAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabourLinkAPI.Migrations
{
    [DbContext(typeof(LabourLinkDbContext))]
    partial class LabourLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("json");

                    b.Property<string>("OldValues")
                        .HasColumnType("json");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InterviewLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("char(36)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("ApplyCount")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EducationRequired")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FeaturedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobCategory")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RequiredExperience")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Location");

                    b.HasIndex("Status");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobSeeker", b =>
                {
                    b.Property<Guid>("JobSeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("AvailabilityDate")
                        .HasColumnType("date");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesiredJobRole")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DesiredLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExpectedSalary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("JobSeekerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("job_seekers", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.LookupValue", b =>
                {
                    b.Property<int>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("LookupId");

                    b.HasIndex("Category", "Value")
                        .IsUnique();

                    b.ToTable("lookup_values", (string)null);

                    b.HasData(
                        new
                        {
                            LookupId = 1,
                            Category = "UserRole",
                            Name = "Worker",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 2,
                            Category = "UserRole",
                            Name = "JobSeeker",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 3,
                            Category = "UserRole",
                            Name = "RecruitmentAgency",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 4,
                            Category = "UserRole",
                            Name = "Administrator",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 5,
                            Category = "UserStatus",
                            Name = "Active",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 6,
                            Category = "UserStatus",
                            Name = "Inactive",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 7,
                            Category = "UserStatus",
                            Name = "Suspended",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 8,
                            Category = "UserStatus",
                            Name = "Banned",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 9,
                            Category = "Gender",
                            Name = "Male",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 10,
                            Category = "Gender",
                            Name = "Female",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 11,
                            Category = "Gender",
                            Name = "Other",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 12,
                            Category = "VerificationStatus",
                            Name = "Pending",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 13,
                            Category = "VerificationStatus",
                            Name = "Verified",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 14,
                            Category = "VerificationStatus",
                            Name = "Rejected",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 15,
                            Category = "EmploymentType",
                            Name = "FullTime",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 16,
                            Category = "EmploymentType",
                            Name = "PartTime",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 17,
                            Category = "EmploymentType",
                            Name = "Contract",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 18,
                            Category = "EmploymentType",
                            Name = "Seasonal",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 19,
                            Category = "EducationLevel",
                            Name = "Primary",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 20,
                            Category = "EducationLevel",
                            Name = "Secondary",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 21,
                            Category = "EducationLevel",
                            Name = "Diploma",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 22,
                            Category = "EducationLevel",
                            Name = "Degree",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 23,
                            Category = "EducationLevel",
                            Name = "Masters",
                            Value = 5
                        },
                        new
                        {
                            LookupId = 24,
                            Category = "EducationLevel",
                            Name = "PhD",
                            Value = 6
                        },
                        new
                        {
                            LookupId = 25,
                            Category = "JobStatus",
                            Name = "Draft",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 26,
                            Category = "JobStatus",
                            Name = "Published",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 27,
                            Category = "JobStatus",
                            Name = "Closed",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 28,
                            Category = "JobStatus",
                            Name = "Expired",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 29,
                            Category = "ComplaintStatus",
                            Name = "Submitted",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 30,
                            Category = "ComplaintStatus",
                            Name = "UnderReview",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 31,
                            Category = "ComplaintStatus",
                            Name = "InProgress",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 32,
                            Category = "ComplaintStatus",
                            Name = "Resolved",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 33,
                            Category = "ComplaintStatus",
                            Name = "Closed",
                            Value = 5
                        },
                        new
                        {
                            LookupId = 34,
                            Category = "ComplaintStatus",
                            Name = "Rejected",
                            Value = 6
                        },
                        new
                        {
                            LookupId = 35,
                            Category = "ComplaintType",
                            Name = "SalaryDispute",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 36,
                            Category = "ComplaintType",
                            Name = "UnsafeConditions",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 37,
                            Category = "ComplaintType",
                            Name = "HealthConcern",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 38,
                            Category = "ComplaintType",
                            Name = "LivingFacilities",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 39,
                            Category = "ComplaintType",
                            Name = "Harassment",
                            Value = 5
                        },
                        new
                        {
                            LookupId = 40,
                            Category = "ComplaintType",
                            Name = "Other",
                            Value = 6
                        },
                        new
                        {
                            LookupId = 41,
                            Category = "ApplicationStatus",
                            Name = "Pending",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 42,
                            Category = "ApplicationStatus",
                            Name = "UnderReview",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 43,
                            Category = "ApplicationStatus",
                            Name = "Shortlisted",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 44,
                            Category = "ApplicationStatus",
                            Name = "Rejected",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 45,
                            Category = "ApplicationStatus",
                            Name = "Accepted",
                            Value = 5
                        },
                        new
                        {
                            LookupId = 46,
                            Category = "ApplicationStatus",
                            Name = "Withdrawn",
                            Value = 6
                        },
                        new
                        {
                            LookupId = 47,
                            Category = "NewsCategory",
                            Name = "Alert",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 48,
                            Category = "NewsCategory",
                            Name = "Update",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 49,
                            Category = "NewsCategory",
                            Name = "Opportunity",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 50,
                            Category = "NewsCategory",
                            Name = "Regulation",
                            Value = 4
                        },
                        new
                        {
                            LookupId = 51,
                            Category = "Priority",
                            Name = "Low",
                            Value = 1
                        },
                        new
                        {
                            LookupId = 52,
                            Category = "Priority",
                            Name = "Medium",
                            Value = 2
                        },
                        new
                        {
                            LookupId = 53,
                            Category = "Priority",
                            Name = "High",
                            Value = 3
                        },
                        new
                        {
                            LookupId = 54,
                            Category = "Priority",
                            Name = "Critical",
                            Value = 4
                        });
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("NewsId");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("IsPublished");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.RecruitmentAgency", b =>
                {
                    b.Property<Guid>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("OperatingCountries")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("AgencyId");

                    b.HasIndex("CompanyRegistrationNumber")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VerifiedBy");

                    b.ToTable("recruitment_agencies", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("TokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.SavedJob", b =>
                {
                    b.Property<Guid>("SavedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("char(36)");

                    b.HasKey("SavedJobId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.Worker", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DesiredLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("WorkerRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("WorkerId");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VerifiedBy");

                    b.HasIndex("WorkerRegistrationNumber")
                        .IsUnique();

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.WorkerComplaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToAdminId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ComplaintType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("char(36)");

                    b.HasKey("ComplaintId");

                    b.HasIndex("AssignedToAdminId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId");

                    b.ToTable("worker_complaints", (string)null);
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobApplication", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.JobPosting", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabourLinkAPI.Models.Entities.JobSeeker", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabourLinkAPI.Models.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedApplications")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabourLinkAPI.Models.Entities.Worker", "Worker")
                        .WithMany("JobApplications")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("JobSeeker");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobPosting", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.RecruitmentAgency", "Agency")
                        .WithMany("JobPostings")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobSeeker", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithOne("JobSeeker")
                        .HasForeignKey("LabourLinkAPI.Models.Entities.JobSeeker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.News", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "CreatedByAdmin")
                        .WithMany("CreatedNews")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.RecruitmentAgency", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithOne("Agency")
                        .HasForeignKey("LabourLinkAPI.Models.Entities.RecruitmentAgency", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabourLinkAPI.Models.Entities.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.SavedJob", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.JobPosting", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabourLinkAPI.Models.Entities.JobSeeker", "JobSeeker")
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.Worker", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("LabourLinkAPI.Models.Entities.Worker", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabourLinkAPI.Models.Entities.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.WorkerComplaint", b =>
                {
                    b.HasOne("LabourLinkAPI.Models.Entities.User", "AssignedToAdmin")
                        .WithMany("AssignedComplaints")
                        .HasForeignKey("AssignedToAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabourLinkAPI.Models.Entities.Worker", "Worker")
                        .WithMany("Complaints")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToAdmin");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.JobSeeker", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.RecruitmentAgency", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Agency");

                    b.Navigation("AssignedComplaints");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedNews");

                    b.Navigation("JobSeeker");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedApplications");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("LabourLinkAPI.Models.Entities.Worker", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("JobApplications");
                });
#pragma warning restore 612, 618
        }
    }
}